### ISSUE TITLE
Path to esptool.exe in platforms.txt not obeyed.

### ISSUE THREAD

**Issue by nl0pvm** [rogerclarkmelbourne/arduino-esp8266#4]
I just downloaded the zip and installed it. However when compiling I get the following error.

`Cannot run program "C:\Users\#USER#\Documents\Arduino\hardware\arduino-esp8266-master/tools/esptool": CreateProcess error=2, Het systeem kan het opgegeven bestand niet vinden`

I solved it by moving the file however it seems that the path in `platforms.txt` is not obeyed.

My environment: `Arduino: 1.6.3 (Windows 7), Board:"Generic ESP8266 board"`

**Comment by rogerclarkmelbourne** [comment]
I think there was a clash with 2 different pull requests that I did not notice

The path to the windows folder should be set in the lines near the bottom of platform.txt

I will test and get back to you

**Comment by rogerclarkmelbourne** [comment]
The issue doesn't seem to be the path to the upload, its something else.

However if I copy esptool.exe to /tools it fixes the issue even though its using the copy of esptool.exe in the windows folder

I need to take another look at this, but the latest version should be working (at least for windows)

**Comment by rogerclarkmelbourne** [comment]
My repo has been superseded

Please use 

https://github.com/sandeepmistry/esp8266-Arduino
