### ISSUE TITLE
undefined reference to `__dso_handle'

### ISSUE THREAD

**Issue by nl0pvm** [rogerclarkmelbourne/arduino-esp8266#5]
The issue described at http://www.esp8266.com/viewtopic.php?f=29&t=2196&p=13039&hilit=dso_handle#p13039 is in your environment.

A temporary workaround is adding `void* __dso_handle;` somewhere in your sketch.

**Comment by JeroenBeemster** [comment]
Thanks, I temporary solved in version examples by adding your advise

**Comment by rogerclarkmelbourne** [comment]
@JeroenBeemster 

Can you comment on issue https://github.com/esp8266/Arduino/issues/23#issuecomment-92050063

as it would be handy if we knew how you compiled your esp8266 gcc version, as its different from the one Ivan compiled.
In some ways its better (it doesnt require libiconv-2.dll) but in some ways its worse (Ivan has posted issues with some of the build config settings which cause problems )

Thanks

Roger

**Comment by rogerclarkmelbourne** [comment]
This has been resolved in Sandeep's repo https://github.com/sandeepmistry/esp8266-Arduino
please use it instead of mine ;-)
